## Prétraitement 

In [1]:
import numpy as np

In [ ]:
def ranktransform(x):
    """
    Rank transform of the image input x
    Computes the rank of the intensity of each pixel x in its 7x7 neighborhood
    """
    image = x.astype(np.float32)

    # Traitement des problèmes de bord
    pad = 3 # 7 // 2
    padded = np.pad(image, pad, mode='reflect')

    H, W = image.shape
    rtImage = np.zeros((H, W), dtype=np.float32)
    for x in range(-pad, pad + 1):
        for y in range(-pad, pad + 1):
            if y == 0 and x == 0:  #pixel central
                continue
            neighbor = padded[pad + y: pad + y + H, pad + x: pad + x + W]
            rtImage += (neighbor < image).astype(np.float32)
 
    return rtImage

In [6]:
def test():
    img = np.ones((9, 9), dtype=np.float32) * 0.5
    img[6, 5] = 0.0  
    img[5, 6] = 5.0
    rt = ranktransform(img)
    print(rt)

test()

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  2.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  2.]
 [ 0.  0.  1.  1.  1.  1. 48.  1.  2.]
 [ 0.  0.  1.  1.  1.  0.  1.  1.  2.]
 [ 0.  0.  2.  2.  2.  2.  2.  2.  4.]
 [ 0.  0.  2.  2.  2.  2.  2.  2.  4.]]


Le rang attendu en un minimum est 0. A contrario sur un maximum on attent 48 en rang. 